name: nxviz
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- python=3.6
- matplotlib
- networkx
- numpy
- pip
- setuptools
- pycodestyle
- pydocstyle
- black
- click
- pandas
- coverage
- pytest-cov
- sphinx
- cython
- palettable
- hypothesis
- pytest
- cryptography
- pyyaml
- twine
- seaborn
- pipreqs
- isort
- bumpversion
- more-itertools
- jupyterlab
- pip:
    - sphinxcontrib-fulltoc
