name: nxviz
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - black
  - bump2version>=1.0.1
  - click
  - coverage
  - cryptography
  - cython
  - hypothesis
  - isort
  - jupyter
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib-base
  - more-itertools
  - networkx
  - numpy
  - palettable
  - pandas
  - pip
  - pipreqs
  - pycodestyle
  - pydocstyle
  - pre-commit
  - pyprojroot
  - pylint
  - pytest
  - pytest-cov
  - pyyaml
  - seaborn
  - setuptools
  - sphinx
  - twine
  - mkdocs
  - mkdocs-material
  - pip:
      - mknotebooks
